In [3]:
import torch
import numpy as np

In [4]:
#listas normais
myList = [[1,2,3]]
myList


[[1, 2, 3]]

In [5]:
#listas com numpy
np1 = np.random.rand(3)
np1

array([0.52460817, 0.13308692, 0.15401902])

In [6]:
#listas com tensors
tensor_2d = torch.randn(3)
tensor_2d

tensor([-0.2011, -1.0666, -0.9996])

In [7]:
#conversão
tensor_np = torch.tensor(np1)
tensor_np

tensor([0.5246, 0.1331, 0.1540], dtype=torch.float64)