In [4]:
import torch
import numpy as np

In [5]:
tensor_a = torch.tensor([1,2,3,4])
tensor_b = torch.tensor([5,6,7,8])

In [6]:
#add
tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

In [7]:
#sub
tensor_a - tensor_b

tensor([-4, -4, -4, -4])

In [8]:
#mult
tensor_a * tensor_b

tensor([ 5, 12, 21, 32])

In [9]:
#div
tensor_a / tensor_b

tensor([0.2000, 0.3333, 0.4286, 0.5000])

In [12]:
#remainder
tensor_a % tensor_b

tensor([1, 2, 3, 4])

In [14]:
#expoent
tensor_a ** tensor_b

tensor([    1,    64,  2187, 65536])

In [17]:
#ou..... (vale pra todos)
tensor_a.pow(tensor_b)

tensor([    1,    64,  2187, 65536])

In [20]:
#isso faz com que seja tribuido ao tensor_a um novo valor
#esse underscore embaixo ali
tensor_a.add_(tensor_b)
tensor_a

tensor([ 6,  8, 10, 12])