In [15]:
import torch
myTorch = torch.arange(10)
myTorch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
#Reshape and view
#                         2,6  <- dá erro
myTorch1 = myTorch.reshape(2,5)
myTorch1

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [17]:
#reshape sem saber a quantiade de numeros
myTorch2 = myTorch.reshape(-1,2)
myTorch2

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [21]:
#view
myTorch3 = myTorch.view(-1,5)
myTorch3

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [ ]:
#reshape e view são como ponteiros, alterar o original altera eles

In [25]:
#slices - elementos
myTorch2[:,1]

tensor([1, 3, 5, 7, 9])

In [26]:
#slices - coluna
myTorch2[:,1:]

tensor([[1],
        [3],
        [5],
        [7],
        [9]])